const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('fs');const assert=require('assert/strict');
(async()=>{const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('Not implemented'))errors.push(e.message+' '+(e.cause?.stack||''));});
const root=require('path').resolve(__dirname,'..')+'/';const html=fs.readFileSync(root+'src/index.html','utf8').replace(/<script src="[^"]*"><\/script>/g,'');
const dom=new JSDOM(html,{runScripts:'outside-only',url:'http://localhost',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;w.structuredClone=structuredClone;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.__TAURI__={core:{invoke:async(cmd,args)=>{if(cmd==='vault_status')return {configured:true};if(cmd==='save_state'){w.savedState=args.stateJson;return {}};if(cmd==='list_attachments')return [];if(cmd==='export_backup')return {payloadJson:'{}'};return {}}}};w.URL.createObjectURL=()=>'';w.URL.revokeObjectURL=()=>{};
w.eval(fs.readFileSync(root+'src/dossier-core.js','utf8'));const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1];
// Evaluate both scripts together so lexical data bindings stay available in jsdom eval.
w.eval(script+'\n'+fs.readFileSync(root+'src/dossier-ui.js','utf8')+`\nwindow.testState=()=>data;window.fixture=()=>{data=Dossier.normalize({...structuredClone(seed),students:[{id:'test-a',first:'Anna',last:'Beispiel',className:'5a',schoolYear:'2026/27',active:true,enrollments:[{className:'5a',schoolYear:'2026/27',validFrom:'2026-08-01'}]},{id:'test-b',first:'Bert',last:'Beispiel',className:'5a',schoolYear:'2026/27',active:true}],teachers:[{id:'teacher-1',first:'Heike',last:'Muster',classLead:'5a',status:'aktiv'}],cases:[],contacts:[],tasks:[],journal:[],settings:{...seed.settings,classLeads:{},currentSchoolYear:'2026/27',dossierVersion:1}});vaultReady=true;document.getElementById('authGate').classList.add('hidden');renderAll();showStudent('test-a');};window.testYear=()=>{pendingYearChange=Dossier.preview(data,[{givenId:'test-a',first:'Anna',last:'Beispiel',className:'6a',schoolYear:'2027/28'}],{year:'2027/28',effectiveDate:'2027-08-01',classLeads:{'6a':'Neue Leitung'}});renderYearReview();Dossier.apply(data,pendingYearChange);renderAll();showStudent('test-a');};`);
w.fixture();assert.match(w.document.getElementById('studentDetailBody').textContent,/Zeitachse · von oben nach unten lesen/);assert.match(w.document.getElementById('studentDetailBody').textContent,/Klassenleitung: Muster, Heike/);assert.match(w.document.getElementById('studentDetailBody').textContent,/KI-Arbeitsprompt/);assert(w.document.querySelector('.dossier-ampel.grau'));assert(!w.document.querySelector('#studentModal .dialogfoot').textContent.includes('Fallstatus'));console.log('boot ok');
w.testState().cases.push({id:'test-case-a',studentId:'test-a',reason:'Gespräch',status:'Beobachtung',last:'2026-09-15',contacts:1});w.renderCases();w.renderKanban();w.document.querySelector('#caseTable .namecell button').click();assert.match(w.document.getElementById('studentDetailTitle').textContent,/Anna Beispiel/);assert(w.document.querySelector('#studentModal.open .dossier-timeline'));w.document.querySelector('#kanbanBoard .kanban-card h4 button').click();assert(w.document.querySelector('#studentModal.open .dossier-direction'));console.log('fallarbeit links ok');
async function form(values){const f=w.document.getElementById('dossierEditForm');for(const [k,v]of Object.entries(values)){const el=f.elements.namedItem(k);if(!el)throw Error('Field missing '+k);el.value=v;}await f.onsubmit({preventDefault(){},target:f});await new Promise(r=>setTimeout(r,30));const error=w.document.querySelector('.modal.open:not([id])');if(error)throw Error(error.textContent);}
w.dossierEntry('info');await form({content:'Ergotherapie einmal wöchentlich.',date:'2026-09-15'});assert.equal(w.testState().journal.length,1);assert.equal(w.testState().tasks.length,0);assert.match(w.document.getElementById('studentDetailBody').textContent,/Lokale Handlungsvorschläge/);const suggestion=w.testState().journal[0].actionSuggestions[0];await w.dossierSuggestionIgnore(w.testState().journal[0].id,suggestion.id);assert.equal(suggestion.status,'nicht verwendet');assert.equal(w.testState().tasks.length,0);console.log('info ok');
w.dossierEntry('event');await form({content:'Mutter berichtet: Der Übergang gelingt besser.',date:'2026-09-14',title:'Elterngespräch'});const key='entry:'+w.testState().journal.at(-1).id;w.dossierStep(key);await form({title:'Rückmeldung einholen',assignedTo:'Sabine',due:'2027-09-01'});assert.equal(w.testState().tasks.length,1);w.renderTasks();assert.match(w.document.getElementById('taskList').textContent,/Erledigt markieren/);assert.match(w.document.getElementById('taskList').textContent,/Entfernen/);console.log('task ok');
w.showStudent('test-a');assert(w.document.querySelector('.dossier-legend'));assert(w.document.querySelector('.dossier-event.left'));assert(w.document.querySelector('.dossier-event.right'));assert(w.document.querySelector('.dossier-date-node'));assert(w.document.querySelector('.dossier-today'));assert(w.document.querySelector('.dossier-undated'));console.log('timeline layout ok');
w.testYear();assert.equal(w.testState().students[0].className,'6a');assert.equal(w.testState().journal[0].studentContexts['test-a'].className,'5a');assert.match(w.document.getElementById('studentDetailBody').textContent,/damals Klasse 5a/);console.log('year ok');
w.dossierTask(w.testState().tasks[0].id);await form({status:'erledigt',result:'Rückmeldung erhalten',completedAt:'2027-09-01'});assert.equal(w.testState().tasks[0].done,true);console.log('completion ok');
w.dossierCalendar();w.closeModal('dossierEditModal');w.dossierAssessment();await form({color:'gelb',date:'2027-09-01',reason:'Weitere Klärung nötig',author:'Sabine'});assert.equal(w.testState().assessments.length,1);assert(w.document.querySelector('.dossier-ampel.gelb'));console.log('ampel ok');console.log('errors',errors);if(errors.length)process.exitCode=1;dom.window.close();})();
