import test from 'node:test';
import assert from 'node:assert/strict';
import '../src/dossier-core.js';
const D=globalThis.Dossier;
function fixture(){return D.normalize({settings:{currentSchoolYear:'2026/27',classLeads:{'5a':'Alt'}},students:[{id:'stable-a',first:'Anna',last:'Test',className:'5a',schoolYear:'2026/27',active:true,enrollments:[{schoolYear:'2026/27',className:'5a',validFrom:'2026-08-01',validTo:''}]},{id:'stable-b',first:'Bert',last:'Test',className:'5a',schoolYear:'2026/27',active:true}],cases:[{id:'case-a',studentId:'stable-a'}],contacts:[{id:'old-contact',caseId:'case-a',date:'2026-09-01',content:'Vollständiger Alttext',duration:20}],tasks:[{id:'old-task',caseId:'case-a',due:'2027-09-01',done:false,assignedTo:'Alt'}],documentEvents:[{id:'doc',studentId:'stable-a',date:'2026-09-01',attachmentId:'binary-stays'}],casePlans:[{id:'goal',studentId:'stable-a',date:'2026-09-01',goal:'Erhalten',status:'teilweise'}]});}
function entry(s,extra={}){return D.addEntry(s,{date:'2026-09-15',type:'Elterngespräch / Elternkontakt',content:'Mutter berichtet vollständig.',participantIds:['stable-a'],duration:45,...extra});}
function plan(s,cls='6a'){return D.preview(s,[{givenId:'stable-a',first:'Anna',last:'Test',className:cls,schoolYear:'2027/28'}],{year:'2027/28',effectiveDate:'2027-08-01',classLeads:{[cls]:'Neu'}});}
test('Vollständige Akte bleibt identisch, neue Einträge in derselben Akte, offene Aufgaben und Termine bleiben',()=>{const s=fixture(),e=entry(s);e.pinnedFor=['stable-a'];D.assess(s,'stable-a',{date:'2026-09-15',color:'gelb',reason:'Klärung',author:'Sabine'});const before=structuredClone({journal:s.journal,contacts:s.contacts,tasks:s.tasks,docs:s.documentEvents,goals:s.casePlans,assess:s.assessments});D.apply(s,plan(s));assert.equal(s.students.length,2);assert.equal(s.students[0].id,'stable-a');for(const [k,v]of [['journal',before.journal],['contacts',before.contacts],['documentEvents',before.docs],['casePlans',before.goals],['assessments',before.assess]])assert.deepEqual(s[k],v);assert.equal(s.tasks[0].due,'2027-09-01');assert.equal(s.tasks[0].assignedTo,'Alt');assert.ok(s.tasks[0].assignmentReview);assert.equal(s.students[1].active,true);assert.equal(s.yearTransitions.length,1);const later=entry(s,{date:'2027-09-15'});assert.equal(later.studentContexts['stable-a'].className,'6a');assert.equal(e.studentContexts['stable-a'].className,'5a');assert.equal(s.settings.classLeads['6a'],'Neu');assert.equal(s.classLeadHistory['2026/27']['5a'],'Alt');assert.equal(D.work(s,'stable-a').length,1);});
test('Rückdatierte Einträge und alte Statistik bleiben in damaliger Klasse',()=>{const s=fixture();entry(s);const before=D.journalStats(s,'2026/27','5a');D.apply(s,plan(s));assert.deepEqual(D.journalStats(s,'2026/27','5a'),before);assert.equal(D.journalStats(s,'2026/27','6a').length,0);assert.equal(entry(s,{date:'2026-10-01'}).studentContexts['stable-a'].className,'5a');assert.equal(D.recordContext(s,s.contacts[0],'stable-a').className,'5a');});
test('Wiederholte Normalisierung und Import erzeugen weder Akten- noch Chronologieduplikate',()=>{const s=fixture(),p=plan(s);entry(s);D.apply(s,p);const first=structuredClone(s);D.normalize(s);D.apply(s,p);assert.equal(s.students.length,first.students.length);assert.equal(s.yearTransitions.length,first.yearTransitions.length);assert.deepEqual(s.journal,first.journal);});
test('Name allein ist kein Treffer; gespeicherte externe ID bleibt verlässlich',()=>{const s=fixture();let p=D.preview(s,[{first:'Anna',last:'Test',className:'6a',schoolYear:'2027/28'}],{year:'2027/28',effectiveDate:'2027-08-01'});assert.equal(p.rows[0].action,'review');assert.throws(()=>D.apply(s,p));p.rows[0].studentId='stable-a';p.rows[0].action='update';p.rows[0].confirmed=true;p.rows[0].pupil.givenId='external-123';D.apply(s,p);assert.equal(D.lookup(s,{givenId:'external-123',first:'Anna',last:'Test'},'Schülerliste').studentId,'stable-a');});
test('Gleiche Namen, fremde ID und doppelte Zuordnungen müssen geprüft werden',()=>{const s=fixture();s.students.push({...structuredClone(s.students[0]),id:'other-a'});assert.equal(D.lookup(s,{first:'Anna',last:'Test'},'Schülerliste').studentId,'');const p=plan(s);p.rows.push(structuredClone(p.rows[0]));assert.throws(()=>D.apply(s,p),/mehrfach/);const old=structuredClone(s);p.rows[0].pupil.className='99z';assert.throws(()=>D.apply(s,p));assert.deepEqual(s,old);});
test('Wiederholung, Überspringen, Parallelklasse und SKG-Übergang sind möglich',()=>{for(const cls of ['5a','7b','6c','1a']){const s=fixture();if(cls==='1a'){s.students[0].className='SKG 1';s.students[0].enrollments[0].className='SKG 1';}D.apply(s,plan(s,cls));assert.equal(s.students[0].className,cls);assert.equal(s.students[0].enrollments.length,2);}});
test('Fehlende Kinder unverändert; bestätigter Abgang lässt offene Aufgaben bestehen',()=>{const s=fixture();const p=plan(s);assert.equal(p.rows[1].action,'keep');D.apply(s,p);assert.equal(s.students[1].active,true);D.archive(s,'stable-a','2027-08-02','Bestätigter Schulwechsel');assert.equal(s.students[0].active,false);assert.equal(D.work(s,'stable-a')[0].done,false);assert.equal(s.contacts.length,1);assert.equal(s.documentEvents.length,1);});
test('Elterngespräch: zwei parallele Schritte, Rückmeldung mit Ursprung ohne Kopien',()=>{const s=fixture(),e=entry(s);for(let i=0;i<2;i++)D.addTask(s,{title:'Schritt '+i,assignedTo:'Sabine',due:'2026-09-20',participantIds:e.participantIds,sourceEntryKey:'entry:'+e.id});const r=entry(s,{type:'Rückmeldung',date:'2026-09-21',sourceEntryKey:'entry:'+e.id});const tl=D.timeline(s,'stable-a');assert.equal(tl.filter(x=>x.sourceEntryKey==='entry:'+e.id).length,3);assert.equal(r.sourceEntryKey,'entry:'+e.id);});
test('Lokale Vorschläge entstehen ohne Aufgabe und bleiben unverbindlich',()=>{const s=fixture(),e=entry(s,{type:'Trainingsraumbesuch',content:'Rückkehr in den Unterricht wurde besprochen.'});assert.ok(e.actionSuggestions.length>=2&&e.actionSuggestions.length<=3);assert.match(e.actionSuggestions.map(x=>x.title).join(' '),/Reflexionsgespräch/);assert.equal(e.actionSuggestions.every(x=>x.status==='offen'),true);assert.equal(s.tasks.length,1);});
test('Zusatzinfo und geplante OP verändern weder Ampel noch Aufgaben; Zeitablauf bestätigt nichts',()=>{const s=fixture();const before=s.tasks.length;entry(s,{type:'zusätzliche Information',content:'Ergotherapie'});const op=entry(s,{type:'zusätzliche Information',content:'OP geplant',planned:true,plannedDate:'2026-10-01'});assert.equal(s.tasks.length,before);assert.equal(D.currentAssessment(s,'stable-a'),null);D.normalize(s);assert.equal(op.planned,true);assert.equal(D.journalStats(s).length,0);});
test('Gruppe zählt einmal, 20 Teilnahmen, 45 Minuten je Fachkraft; individuelle Notiz isoliert',()=>{const s=fixture();for(let i=2;i<20;i++)s.students.push({id:'p'+i,className:'5a',schoolYear:'2026/27'});const e=entry(s,{participantIds:s.students.map(s=>s.id),individualNotes:{'stable-a':'Nur Anna'},facilitators:['Sabine','Edmund']});const stat=D.journalStats(s);assert.equal(stat.length,1);assert.equal(stat[0].participantIds.length,20);assert.equal(stat[0].duration,90);assert.equal(D.timeline(s,'stable-b').find(x=>x.id===e.id).individualNote,'');D.editEntry(s,e,{content:'Gemeinsame Korrektur'},'Sabine');assert.equal(D.timeline(s,'stable-b').find(x=>x.id===e.id).content,'Gemeinsame Korrektur');assert.equal(e.revisions[0].before.content,'Mutter berichtet vollständig.');});
test('Aufgabenverschiebung erhält Datensatz und Verlauf, Abschluss bewertet kein Ziel',()=>{const s=fixture(),t=D.addTask(s,{title:'Nachfragen',assignedTo:'Edmund',due:'2026-09-01',participantIds:['stable-a']});const count=s.tasks.length;D.setTask(s,t,{due:'2026-10-01',status:'wartet auf Rückmeldung'},'Edmund');assert.equal(s.tasks.length,count);assert.equal(t.history[0].due,'2026-09-01');D.setTask(s,t,{status:'erledigt',result:'Antwort erhalten'},'Edmund');assert.equal(s.casePlans[0].status,'teilweise');assert.equal(D.currentAssessment(s,'stable-a'),null);});
test('Ampelhistorie bleibt einschließlich originalem Datum erhalten',()=>{const s=fixture();D.assess(s,'stable-a',{date:'2026-09-10',color:'rot',reason:'Zeitnah handeln',author:'Edmund'});D.assess(s,'stable-a',{date:'2026-09-15',color:'gelb',reason:'Rückmeldung liegt vor',author:'Sabine'});D.apply(s,plan(s));assert.equal(s.assessments.length,2);assert.equal(D.currentAssessment(s,'stable-a').date,'2026-09-15');assert.equal(D.currentAssessment(s,'stable-a').color,'gelb');});
test('Unbekannte historische Klasse wird nicht erfunden',()=>{const s=fixture();const e=entry(s,{date:'2023-09-15'});assert.equal(e.studentContexts['stable-a'].className,'');assert.equal(e.studentContexts['stable-a'].unknown,true);});

test('Technische Fallstatus stehen nicht zusätzlich in der Schülerchronologie',()=>{const s=fixture();const legacy=[{id:'status-1',eventKind:'Fallstatus',title:'Erste Kontaktaufnahme',date:'2026-09-14',studentId:'stable-a'},{id:'status-2',eventKind:'Fallstatus',title:'Rückmeldung ausstehend',date:'2026-09-15',studentId:'stable-a'},{id:'training-1',eventKind:'Trainingsraumbesuch',title:'Trainingsraum',date:'2026-09-14',studentId:'stable-a'}];assert.deepEqual(D.timeline(s,'stable-a',legacy).filter(e=>e.legacy).map(e=>e.id),['training-1']);});

test('Gesprächsinhalte überstehen erneutes Laden ohne Zeichenänderung',()=>{const s=fixture();const e=entry(s,{content:'„Mutter“ sagt: 2 < 3 & \"gut\".'});const raw=JSON.parse(JSON.stringify(s));const restored=D.restore(raw,o=>JSON.parse(JSON.stringify(o).replaceAll('<','‹').replaceAll('&','＆')));assert.equal(restored.journal[0].content,e.content);});
