/* Lokaler Word-Export ohne externe Dienste oder Abhängigkeiten. */
(function(root){
'use strict';
const enc=new TextEncoder();
const xml=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function crc32(bytes){let c=0xffffffff;for(const byte of bytes){c^=byte;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function zip(entries){const parts=[],central=[];let offset=0;for(const [name,text] of entries){const filename=enc.encode(name),data=enc.encode(text),crc=crc32(data);const local=new Uint8Array(30+filename.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,filename.length,true);local.set(filename,30);parts.push(local,data);const head=new Uint8Array(46+filename.length),h=new DataView(head.buffer);h.setUint32(0,0x02014b50,true);h.setUint16(4,20,true);h.setUint16(6,20,true);h.setUint16(8,0x0800,true);h.setUint32(16,crc,true);h.setUint32(20,data.length,true);h.setUint32(24,data.length,true);h.setUint16(28,filename.length,true);h.setUint32(42,offset,true);head.set(filename,46);central.push(head);offset+=local.length+data.length;}const centralSize=central.reduce((n,p)=>n+p.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);const output=new Uint8Array(offset+centralSize+end.length);let at=0;for(const p of [...parts,...central,end]){output.set(p,at);at+=p.length;}return output;}
function build(title,lines){const runs=value=>String(value??'').split(/\r?\n/).map((part,i)=>(i?'<w:br/>':'')+'<w:t xml:space="preserve">'+xml(part)+'</w:t>').join('');const paragraph=(value,bold=false)=>`<w:p><w:r>${bold?'<w:rPr><w:b/></w:rPr>':''}${runs(value)}</w:r></w:p>`;const content=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraph(title,true)}${lines.map(line=>paragraph(typeof line==='object'&&line!==null?line.text:line,typeof line==='object'&&line!==null&&line.bold===true)).join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`;return zip([['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'],['word/document.xml',content]]);}
root.DossierDocx={build};
})(globalThis);
