/* Gemeinsamer Arbeitsplatz. Altdaten werden verknüpft angezeigt, nicht kopiert. */
'use strict';
const dossierEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DE=dossierEscape;
const dossierTypes=['Schülergespräch / Einzelberatung','Gruppengespräch / Konfliktklärung / Vermittlung','Elterngespräch / Elternkontakt','schulinterne Abstimmung','Austausch mit Schulpsychologie','Einbeziehung externer Fachkräfte oder Einrichtungen','Fallbesprechung / Helferrunde','Sozialtraining / Klassentraining / Kleingruppenangebot','Präventionsangebot / Gruppenaktivität','Trainingsraumbesuch','Vorfall / Beobachtung','Maßnahme / Vereinbarung / Weitervermittlung','Rückmeldung','Überprüfung / Zielentwicklung','Dokument / Befund','zusätzliche Information','Sonstiges'];
const dossierColors={gruen:'Grün · Stabil',gelb:'Gelb · Klärung erforderlich',rot:'Rot · Zeitnah handeln',grau:'Grau · Noch nicht eingeschätzt'};
let dossierYearFilter='',dossierSearch='',dossierEditing='',dossierSource='',dossierSelectedTask='';
const legacyStudentEvents=studentEvents,legacyShowStudent=showStudent,legacyStatDaten=statDaten,legacyAmpelKind=ampelKind;
const style=document.createElement('style');style.textContent=`
.dossier-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.dossier-timeline{border-left:3px solid #bdd5d3;margin:18px 0 0 8px;padding-left:23px;display:grid;gap:17px}.dossier-card{position:relative;border:1px solid var(--line);padding:15px;border-radius:12px;background:white;scroll-margin:20px}.dossier-card:before{content:'';position:absolute;left:-31px;top:20px;width:11px;height:11px;background:#0f766e;border-radius:50%}.dossier-card.planned{border:2px dashed #6a858f;background:#f8fbfc}.dossier-card summary{cursor:pointer;font-weight:700}.dossier-card p{white-space:pre-wrap;overflow-wrap:anywhere}.dossier-card .preview{font-weight:400;color:var(--muted);margin-top:7px}.dossier-today{padding:12px;background:#123047;color:white;border-radius:10px;scroll-margin:20px}.dossier-links{border-left:2px solid #bdd5d3;padding-left:12px;margin-top:10px;display:grid;gap:6px}.dossier-people{max-height:220px;overflow:auto;border:1px solid var(--line);padding:10px;display:grid;gap:6px}.dossier-people label{font-weight:400}.dossier-modal{z-index:32}.dossier-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.dossier-grid label{display:grid;gap:5px}.dossier-grid .full{grid-column:1/-1}.dossier-review input,.dossier-review select{max-width:230px;width:100%}.dossier-review td{vertical-align:top}.dossier-pin{border-left:4px solid #0f766e;padding:10px;margin:8px 0;background:#eff8f7}.dossier-color{font-size:17px}.dossier-color.rot{border-left:5px solid #dc2626}.dossier-color.gelb{border-left:5px solid #e2a400}.dossier-color.gruen{border-left:5px solid #168449}.dossier-color.grau{border-left:5px solid #82949a}.dossier-card .tag{white-space:normal}.dossier-card small{font-weight:400}.dossier-modal textarea{min-height:90px}@media(max-width:700px){.dossier-grid{grid-template-columns:1fr}}
`;document.head.append(style);
const modal=document.createElement('div');modal.id='dossierEditModal';modal.className='modal dossier-modal';modal.innerHTML='<div class="dialog wide"><div class="dialoghead"><h2 id="dossierEditTitle"></h2><button class="close" onclick="closeModal(\'dossierEditModal\')">×</button></div><form id="dossierEditForm"><div class="dialogbody" id="dossierEditBody"></div><div class="dialogfoot"><button type="button" class="btn" onclick="closeModal(\'dossierEditModal\')">Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form></div>';document.body.append(modal);
function dossierField(name,label,value='',type='text',required=false){return `<label>${DE(label)}<input class="field" name="${name}" type="${type}" value="${DE(value)}" ${required?'required':''}></label>`;}
function dossierText(name,label,value='',required=false){return `<label class="full">${DE(label)}<textarea class="field" id="ds-${name}" name="${name}" ${required?'required':''}>${DE(value)}</textarea></label>`;}
function dossierOptions(values,selected){return values.map(v=>`<option ${v===selected?'selected':''}>${DE(v)}</option>`).join('');}
function dossierPopup(title,body,submit){document.getElementById('dossierEditTitle').textContent=title;document.getElementById('dossierEditBody').innerHTML=body;document.getElementById('dossierEditForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{await submit(new FormData(e.target));}catch(err){appAlert(err.message||String(err));}finally{b.disabled=false;}};openModal('dossierEditModal');enhanceDictationFields();}
async function dossierSave(){Dossier.normalize(data);await persistState();renderAll();sicherungNachSpeichern();}
function dossierRecord(key){const [type,...rest]=key.split(':'),eid=rest.join(':');return (type==='entry'?data.journal:type==='task'?data.tasks:type==='assessment'?data.assessments:type==='year'?data.yearTransitions:[]).find(e=>e.id===eid);}
function dossierRefresh(){showStudent(selectedStudentId);}
function dossierJump(key){dossierYearFilter='';dossierSearch='';dossierRefresh();requestAnimationFrame(()=>document.getElementById('ds-'+key)?.scrollIntoView({block:'center'}));}
function dossierLink(key,label){return `<button class="linkbutton" type="button" onclick="dossierJump('${DE(key)}')">${DE(label)}</button>`;}
function dossierLegacyContent(e){const extra=[];for(const [k,v]of Object.entries(e)){if(typeof v==='string'&&v&&!['id','caseId','studentId','date','createdAt','schoolYear','className','eventKind','title','key','time','content','responsible','sourceKey'].includes(k))extra.push(k+': '+v);}return [e.content,...(e.details||[]),...extra].filter(Boolean).join('\n');}
function dossierCard(e){
 const sid=selectedStudentId,own=e.key.startsWith('entry:'),body=e.legacy?dossierLegacyContent(e):e.content||'',date=e.date?fmt(e.date):'Datum nicht bekannt',cl=e.context||{};
 const children=data.tasks.filter(t=>t.sourceEntryKey===e.key),responses=data.journal.filter(r=>r.sourceEntryKey===e.key);
 const status=e.task?(e.done?e.status||'erledigt':e.due&&e.due<today()?'überfällig · '+e.status:e.status):e.planned?'Geplant · Durchführung nicht bestätigt':'';
 const extras=[['Sicht des Kindes',e.childView],['Angaben anderer Beteiligter',e.otherView],['Eigene Beobachtung',e.observation],['Fachliche Einschätzung',e.assessment],['Vereinbarungen',e.agreement],['Ziele',e.goal],['Ergebnis / Wirkung',e.result],['Entscheidung',e.decision],['Quelle',e.source],['Besteht seit',e.since],['Bezugsdatum',e.referenceDate],['Individuelle Ergänzung für dieses Kind',e.individualNote],['Beteiligte Personen',e.people],['Zuständigkeit prüfen',e.assignmentReview]];
 return `<article class="dossier-card ${e.planned?'planned':''}" id="ds-${DE(e.key)}"><small>${DE(date)} ${e.time?DE(e.time):''} · ${DE(e.eventKind)} · ${DE(cl.schoolYear||'Schuljahr unbekannt')} · ${DE(cl.className?'damals Klasse '+cl.className:'damalige Klasse unbekannt')}</small>${status?`<div class="tag ${status.includes('überfällig')?'red':'gray'}">${DE(status)}</div>`:''}<details><summary>${DE(e.title||e.eventKind)}<div class="preview">${DE(body.slice(0,160))}${body.length>160?' …':''}</div></summary><p>${DE(body)}</p>${extras.filter(([,v])=>v).map(([k,v])=>`<p><strong>${DE(k)}:</strong> ${DE(v)}</p>`).join('')}<small>Erfasst ${DE(e.createdAt?fmt(e.createdAt):'Datum unbekannt')} · dokumentiert von ${DE(e.responsible||e.author||e.assignedTo||'nicht angegeben')}${e.duration?' · '+e.duration+' Minuten':''}</small>${e.plannedDate?`<p>Geplanter Termin: ${DE(fmt(e.plannedDate))} · Durchführung nicht automatisch bestätigt.</p>`:''}${e.dateBasis==='reported'?'<p>Unter Mitteilungsdatum eingeordnet; Bezugsdatum nicht bekannt.</p>':''}${e.revisions?.length?`<details><summary>Änderungshistorie (${e.revisions.length})</summary>${e.revisions.map(r=>`<p>${DE(fmt(r.at))} · ${DE(r.author)}<br>${DE(r.before.content||'')}</p>`).join('')}</details>`:''}${e.history?.length?`<details><summary>Termin- und Statushistorie</summary>${e.history.map(h=>`<p>${DE(fmt(h.at))}: ${DE(h.status)} · ${DE(h.due||'ohne Termin')} · ${DE(h.assignedTo||'')} · ${DE(h.result||'')}</p>`).join('')}</details>`:''}</details>
 ${e.sourceEntryKey?`<div class="dossier-links">Ursprung: ${dossierLink(e.sourceEntryKey,'Ursprungseintrag öffnen')}</div>`:''}
 ${children.length||responses.length?`<div class="dossier-links">${children.map(t=>dossierLink('task:'+t.id,(t.due?fmt(t.due):'Ohne Termin')+' · '+t.title+' · '+(t.status||'offen'))).join('')}${responses.map(r=>dossierLink('entry:'+r.id,fmt(r.date)+' · '+r.title)).join('')}</div>`:''}
 <div class="dossier-toolbar">${e.task?`<button class="btn" onclick="dossierTask('${DE(e.id)}')">Status / Termin / Ergebnis</button>`:`<button class="btn" onclick="dossierStep('${DE(e.key)}')">Nächsten Schritt vereinbaren</button><button class="btn" onclick="dossierEntry('response','${DE(e.key)}')">Rückmeldung eintragen</button><button class="btn" onclick="dossierStep('${DE(e.key)}','Überprüfung')">Überprüfung planen</button>`}${own?`<button class="btn" onclick="dossierEntry('edit','${DE(e.key)}')">Inhalt bearbeiten</button><button class="btn" onclick="dossierPin('${DE(e.id)}')">${e.pinnedFor?.includes(sid)?'Anheftung lösen':'Anheften'}</button>`:''}${e.eventKind==='Dokument'?'<button class="btn" onclick="openAttachments()">Dateien öffnen</button>':''}</div></article>`;
}
showStudent=function(sid){
 const s=data.students.find(s=>s.id===sid);if(!s)return;const changed=selectedStudentId!==sid;selectedStudentId=sid;if(changed){dossierYearFilter='';dossierSearch='';}
 const events=Dossier.timeline(data,sid,legacyStudentEvents(sid)),a=Dossier.currentAssessment(data,sid),oldIndicator=legacyAmpelKind(sid),tasks=Dossier.work(data,sid).filter(t=>!t.done),overdue=tasks.filter(t=>t.due&&t.due<today());
 const years=[...new Set(events.map(e=>e.context?.schoolYear).filter(Boolean))].sort();const chosen=events.filter(e=>(!dossierYearFilter||e.context?.schoolYear===dossierYearFilter||e.task&&!e.done)&&(!dossierSearch||JSON.stringify(e).toLocaleLowerCase('de').includes(dossierSearch)));
 const dated=chosen.filter(e=>e.date),past=dated.filter(e=>e.date<today()),next=dated.filter(e=>e.date>=today()),undated=chosen.filter(e=>!e.date);
 document.getElementById('studentDetailTitle').textContent=`${s.first} ${s.last} · ${s.className} ${s.active===false?'· archiviert':''}`;
 const body=document.getElementById('studentDetailBody');body.dataset.gegliedert='1';body.innerHTML=`
 <div class="dossier-toolbar"><button class="btn primary" onclick="dossierEntry('event')">Ereignis / Gespräch eintragen</button><button class="btn" onclick="dossierEntry('info')">Information hinzufügen</button><button class="btn" onclick="dossierAssessment()">Ampel einschätzen</button><button class="btn" onclick="openAttachments()">Dokumente</button><button class="btn" onclick="dossierCalendar()">Termine / Aufgabenboard</button></div>
 <div class="notice dossier-color ${a?.color||'grau'}"><strong>${dossierColors[a?.color||'grau']}</strong><br>${DE(a?.reason||'Noch keine fachliche Gesamtbewertung dokumentiert.')}<br><small>${a?DE(fmt(a.date)+' · '+a.author):'Die Ampel bewertet den Handlungsbedarf.'}</small>${a?.reviewDate?'<p>Überprüfung vorgesehen: '+DE(fmt(a.reviewDate))+'</p>':''}</div>
 ${oldIndicator.stufe!=='gruen'?'<div class="notice warning"><strong>Fachlich prüfen.</strong> Berechnete Hinweise aus Fehlzeiten, Kontakten oder offenen Aufgaben. Sie verändern die fachliche Ampel nicht.<br>'+DE(oldIndicator.grund||'')+'</div>':''}
 ${tasks.some(t=>t.assignmentReview)?'<div class="notice warning">Offene Zuständigkeiten prüfen: '+tasks.filter(t=>t.assignmentReview).map(t=>dossierLink('task:'+t.id,t.title)).join(' · ')+'</div>':''}
 ${data.journal.filter(e=>e.participantIds.includes(sid)&&e.pinnedFor?.includes(sid)).map(e=>`<div class="dossier-pin"><strong>Angeheftet: ${DE(e.title)}</strong><p>${DE(e.content)}</p>${dossierLink('entry:'+e.id,'Originaleintrag öffnen')}</div>`).join('')}
 <details><summary>Stammdaten, Familie und Klassenverlauf</summary><p>Stabile Schüler-ID: ${DE(s.id)} · ${DE(s.schoolYear)} · Klasse ${DE(s.className)}</p><p>Klassenleitung: ${DE(data.settings.classLeads?.[s.className]||'noch zuordnen')}</p><p>${DE(s.address)} ${DE(s.district)} · ${DE(s.phone)}</p><p>${DE(s.guardian1)} · ${DE(s.guardian2)}</p>${familySummary(s)}${geschwisterBlock(sid)}<ul>${s.enrollments.map(e=>`<li>${DE(e.schoolYear)} · ${DE(e.className)} · ${e.validFrom?DE(fmt(e.validFrom)):'Beginn nicht dokumentiert'}${e.validTo?' bis '+DE(fmt(e.validTo))+' (exklusiv)':' · fortlaufend'}</li>`).join('')}</ul></details>
 <details><summary>Ziele, Maßnahmen und ergänzende Fachansichten</summary>${planSummary(sid)}${outcomeSummary(sid)}${relatedSummary(sid)}${studentAbsencePanel(sid)}<button class="btn" onclick="dossierLegacyDetails()">Bisherige Detailansicht öffnen</button></details>
 <div class="chronicle-tools"><input class="field" placeholder="Chronologie durchsuchen" value="${DE(dossierSearch)}" onchange="dossierSearch=this.value.toLocaleLowerCase('de');dossierRefresh()"><select class="field" onchange="dossierYearFilter=this.value;dossierRefresh()"><option value="">Alle Schuljahre</option>${years.map(y=>`<option ${y===dossierYearFilter?'selected':''}>${DE(y)}</option>`).join('')}</select><button class="btn" onclick="document.getElementById('dossierToday').scrollIntoView({block:'center'})">Heute</button></div>
 <div class="dossier-timeline">${past.map(dossierCard).join('')}<div class="dossier-today" id="dossierToday"><strong>Heute · ${fmt(today())}</strong>${overdue.length?'<p>Überfällig: '+overdue.map(t=>dossierLink('task:'+t.id,t.title)).join(' · ')+'</p>':''}</div>${next.map(dossierCard).join('')}<h3>Offen ohne Termin</h3>${undated.filter(e=>e.task&&!e.done).map(dossierCard).join('')||'<p>Keine offenen Schritte ohne Termin.</p>'}${undated.filter(e=>!e.task||e.done).length?'<h3>Weitere Einträge ohne bekanntes Datum</h3>'+undated.filter(e=>!e.task||e.done).map(dossierCard).join(''):''}</div>`;
 const btn=document.getElementById('studentStatusButton');btn.textContent=s.active===false?'Reaktivieren':'Abgang / Schulwechsel';openModal('studentModal');requestAnimationFrame(()=>document.getElementById('dossierToday')?.scrollIntoView({block:'center'}));
};
function dossierLegacyDetails(){legacyShowStudent(selectedStudentId);document.getElementById('studentDetailBody').insertAdjacentHTML('afterbegin','<button class="btn primary" onclick="dossierRefresh()">Zur gemeinsamen Chronologie</button>');}
function dossierParticipantList(selected){return `<input class="field" type="search" placeholder="Teilnehmende suchen" oninput="this.nextElementSibling.querySelectorAll('label').forEach(l=>l.hidden=!l.textContent.toLowerCase().includes(this.value.toLowerCase()))"><div class="dossier-people">${data.students.filter(s=>s.active!==false||selected.includes(s.id)).sort((a,b)=>a.last.localeCompare(b.last)).map(s=>`<label><input type="checkbox" name="participantIds" value="${DE(s.id)}" ${selected.includes(s.id)?'checked':''}> ${DE(s.last+', '+s.first+' · '+s.className)}</label>`).join('')}</div>`;}
function dossierEntry(mode='event',key='',preset=[]){
 const old=mode==='edit'?dossierRecord(key):null;dossierEditing=old?.id||'';dossierSource=mode==='response'?key:old?.sourceEntryKey||'';const info=mode==='info'||old?.type==='zusätzliche Information';const selected=old?.participantIds||preset.length&&preset||[selectedStudentId].filter(Boolean);
 const e=old||{};
 dossierPopup(info?'Information hinzufügen':old?'Gemeinsamen Inhalt bearbeiten':'Ereignis / Gespräch eintragen',`<div class="dossier-grid">
 ${dossierField('date',info?'Mitteilungsdatum':'Ereignisdatum',e.date||today(),'date',true)}${dossierField('responsible','Dokumentiert von',e.responsible||data.settings.activeUser||'Edmund','text',true)}
 <label>Eintragsart<select class="field" name="type">${dossierOptions(dossierTypes,e.type||(info?'zusätzliche Information':mode==='response'?'Rückmeldung':dossierTypes[0]))}</select></label>${dossierField('title','Kurzer Titel (optional)',e.title||'')}
 ${dossierText('content',info?'Information':'Gesprächsinhalt',e.content||'',true)}${dossierField('source','Informationsquelle (optional)',e.source||'')}${dossierField('people','Beteiligte Personen (optional)',e.people||'')}
 <details class="full" ${selected.length!==1?'open':''}><summary>Zuordnung prüfen: ${selected.length} Kind(er) vorausgewählt</summary><p>Nur tatsächlich Teilnehmende auswählen. Abwesende Kinder abwählen.</p>${old?'<p>Bei Bearbeitung bleibt die ursprüngliche Teilnahme erhalten. Individuelle Angaben gelten nur für das ausgewählte Kind.</p>':''}${dossierParticipantList(selected)}</details>
 <details class="full"><summary>Weitere Angaben bei Bedarf</summary><div class="dossier-grid">
 ${dossierField('time','Uhrzeit',e.time||'','time')}${dossierField('channel','Kontaktweg',e.channel||'')}${dossierField('referenceDate','Bezugsdatum (falls bekannt)',e.referenceDate||'','date')}${dossierField('since','Besteht seit (falls bekannt)',e.since||'')}
 ${dossierText('childView','Sicht / Aussagen des Kindes',e.childView||'')}${dossierText('otherView','Angaben anderer Beteiligter',e.otherView||'')}${dossierText('observation','Eigene Beobachtung',e.observation||'')}${dossierText('assessment','Fachliche Einschätzung',e.assessment||'')}${dossierText('agreement','Vereinbarungen',e.agreement||'')}${dossierText('goal','Ziele',e.goal||'')}${dossierText('result','Ergebnis / Wirkung',e.result||'')}
 <label>Entscheidung zur Unterstützung<select class="field" name="decision">${dossierOptions(['','fortführen','anpassen','abschließen'],e.decision||'')}</select></label>${dossierField('duration','Dauer in Minuten',e.duration||0,'number')}${dossierField('facilitators','Durchführende (mit Semikolon trennen)',e.facilitators?.join('; ')||'')}
 ${dossierText('individualNote','Individuelle Ergänzung nur für '+(data.students.find(s=>s.id===selectedStudentId)?.first||'das ausgewählte Kind'),e.individualNotes?.[selectedStudentId]||'')}
 <label><span><input name="planned" type="checkbox" ${e.planned?'checked':''}> Geplant, Durchführung noch nicht bestätigt</span></label>${dossierField('plannedDate','Geplanter Termin (z. B. OP)',e.plannedDate||'','date')}
 <label class="full">Dokumente zur Akte (PDF, JPG, PNG bis 5 MB)<input name="attachments" type="file" accept="application/pdf,image/jpeg,image/png" multiple></label></div></details></div>`,async fd=>{
 const f=Object.fromEntries(fd);const participantIds=fd.getAll('participantIds');if(!participantIds.length)throw Error('Mindestens ein Kind auswählen.');if(f.plannedDate&&!fd.has('planned'))throw Error('Für einen geplanten Termin bitte „Geplant“ markieren oder den Termin entfernen.');
 const files=fd.getAll('attachments').filter(f=>f.size);if(files.length&&participantIds.length!==1)throw Error('Dokumente bitte in der jeweiligen Einzelakte hinzufügen.');
 for(const file of files)if(!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.size>5*1024*1024)throw Error('Dokument muss PDF, JPG oder PNG bis 5 MB sein.');
 const individualNotes={...(old?.individualNotes||{})};if(f.individualNote&&selectedStudentId&&!participantIds.includes(selectedStudentId))throw Error('Das Kind für die individuelle Notiz muss teilnehmen.');if(selectedStudentId)individualNotes[selectedStudentId]=f.individualNote||'';
 const record={...f,participantIds,title:f.title||f.content.slice(0,70),planned:fd.has('planned'),sourceEntryKey:dossierSource,individualNotes,dateBasis:info&&!f.referenceDate?'reported':'event',facilitators:f.facilitators.split(';').map(s=>s.trim()).filter(Boolean)};delete record.attachments;delete record.individualNote;
 let saved;if(old){if(JSON.stringify([...participantIds].sort())!==JSON.stringify([...old.participantIds].sort()))throw Error('Teilnahme beim Bearbeiten unverändert lassen.');Dossier.editEntry(data,old,record,f.responsible);saved=old;}else saved=Dossier.addEntry(data,record);
 await dossierSave();
 for(const file of files){const result=await invoke('put_attachment',{studentId:participantIds[0],name:clean(file.name),mimeType:file.type,bytes:Array.from(new Uint8Array(await file.arrayBuffer()))});data.documentEvents.push({id:Dossier.uid('doc'),attachmentId:result.id,studentId:participantIds[0],date:f.date,name:file.name,action:'Dokument zum Chronologieeintrag',sourceEntryKey:'entry:'+saved.id});}
 if(files.length)await dossierSave();closeModal('dossierEditModal');if(selectedStudentId)dossierRefresh();else{selectedStudentId=participantIds[0];dossierRefresh();}dossierSuggestions(saved);
 });
 if(old){const form=document.getElementById('dossierEditForm');form.elements.date.readOnly=true;}
}
function dossierSuggestions(e){if(e.type==='zusätzliche Information')return;const hints=/Eltern/.test(e.type)?'Rückmeldung vereinbaren?':/Trainingsraum/.test(e.type)?'Reflexionsgespräch sinnvoll?':/Überprüfung/.test(e.type)?'Unterstützung fortführen, anpassen oder abschließen?':'Überprüfung oder Rückmeldung planen?';const el=document.getElementById('studentDetailBody');el.insertAdjacentHTML('afterbegin',`<div class="notice"><strong>Vorschlag: ${DE(hints)}</strong><p>Es wurde kein zusätzlicher Termin angelegt.</p><button class="btn" onclick="dossierStep('entry:${DE(e.id)}','Überprüfung')">Schritt selbst vereinbaren</button> <button class="btn" onclick="this.parentElement.remove()">Ohne weiteren Schritt</button></div>`);el.closest('.dialog').scrollTop=0;}
async function dossierPin(eid){const e=data.journal.find(e=>e.id===eid);if(!e)return;e.pinnedFor=e.pinnedFor||[];e.pinHistory=e.pinHistory||[];const was=e.pinnedFor.includes(selectedStudentId);e.pinnedFor=was?e.pinnedFor.filter(s=>s!==selectedStudentId):[...e.pinnedFor,selectedStudentId];e.pinHistory.push({at:new Date().toISOString(),studentId:selectedStudentId,pinned:!was});await dossierSave();dossierRefresh();}
function dossierStep(key,type='Nächster Schritt'){
 const origin=dossierRecord(key),participantIds=origin?Dossier.ids(data,origin):[selectedStudentId];
 dossierPopup(type,`<div class="dossier-grid">${dossierText('title','Was soll geschehen?','',true)}${dossierField('assignedTo','Wer ist zuständig?','','text',true)}${dossierField('due','Bis wann / wann? (optional)','','date')}${dossierText('expectedResult','Wozu / welches Ziel?')}<p class="full">Verknüpft mit ${participantIds.length} Schülerakte(n). Ohne Datum erscheint der Schritt unter „Offen ohne Termin“.</p></div>`,async fd=>{const f=Object.fromEntries(fd);Dossier.addTask(data,{...f,participantIds,sourceEntryKey:key,taskType:type,caseId:'',priority:'Normal'});await dossierSave();closeModal('dossierEditModal');dossierRefresh();});
}
function dossierTask(tid){
 const t=data.tasks.find(t=>t.id===tid);if(!t)return;
 dossierPopup('Schritt bearbeiten',`<div class="dossier-grid">${dossierText('title','Was soll geschehen?',t.title,true)}${dossierField('assignedTo','Zuständigkeit',t.assignedTo||'','text',true)}${dossierField('due','Termin (optional)',t.due||'','date')}<label>Status<select class="field" name="status">${dossierOptions(['offen','in Bearbeitung','wartet auf Rückmeldung','erledigt','entfällt'],t.status||'offen')}</select></label>${dossierText('result','Was kam dabei heraus? / Grund für Entfall',t.result||'')}${dossierField('completedAt','Ergebnisdatum',t.completedAt||today(),'date')}<label><span><input type="checkbox" name="next"> Weiterer Schritt nötig</span></label>${t.assignmentReview?'<label><span><input type="checkbox" name="reviewed"> Zuständigkeit geprüft</span></label>':''}</div>`,async fd=>{const f=Object.fromEntries(fd);Dossier.setTask(data,t,{title:f.title,assignedTo:f.assignedTo,due:f.due,status:f.status,result:f.result,completedAt:f.completedAt},data.settings.activeUser||'SSA');if(fd.has('reviewed'))delete t.assignmentReview;await dossierSave();closeModal('dossierEditModal');if(selectedStudentId)dossierRefresh();if(fd.has('next'))dossierStep('task:'+t.id);});
}
function dossierAssessment(){const a=Dossier.currentAssessment(data,selectedStudentId);dossierPopup('Fachlichen Handlungsbedarf einschätzen',`<div class="dossier-grid"><label>Bewertung<select class="field" name="color">${Object.entries(dossierColors).map(([k,v])=>`<option value="${k}" ${a?.color===k?'selected':''}>${v}</option>`).join('')}</select></label>${dossierField('date','Bewertungsdatum',today(),'date',true)}${dossierField('author','Bewertende Person',data.settings.activeUser||'Edmund','text',true)}${dossierText('reason','Begründung','',true)}${dossierField('reviewDate','Erneute Einschätzung vorgesehen (optional)','','date')}<p>Eine Aufgabe wird nur über „Nächsten Schritt vereinbaren“ angelegt.</p></div>`,async fd=>{Dossier.assess(data,selectedStudentId,Object.fromEntries(fd));await dossierSave();closeModal('dossierEditModal');dossierRefresh();});}
ampelKind=function(sid){const a=Dossier.currentAssessment(data,sid);return a?{stufe:a.color,grund:a.reason,gruende:[],date:a.date}:{stufe:'grau',grund:'Noch nicht fachlich eingeschätzt',gruende:[]};};
function dossierMakePreview(pupils,year,classLeads={}){pendingYearChange=Dossier.preview(data,pupils,{year,classLeads,effectiveDate:year===data.settings.currentSchoolYear?today():year.slice(0,4)+'-08-01'});renderYearReview();openModal('yearReviewModal');}
function importStudents(event){previewStudentImport(event);}
function previewStudentImport(event){const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>5*1024*1024){appAlert('Datei ist größer als 5 MB.');return;}file.text().then(text=>{const p=parseStudentRows(text,file.name);dossierMakePreview(p.pupils,p.schoolYear,p.classLeads);}).catch(err=>appAlert(err.message));}
function dossierManualYear(){const next=nextSchoolYear(data.settings.currentSchoolYear);const pupils=data.students.filter(s=>s.active!==false).map(s=>({givenId:s.id,first:s.first,last:s.last,className:s.className,schoolYear:next}));dossierMakePreview(pupils,next);for(const r of pendingYearChange.rows){r.confirmed=false;r.reason='';}renderYearReview();}
function dossierYearAction(i,value){const r=pendingYearChange.rows[i];if(value==='new'){r.studentId='';r.action='new';}else if(['skip','keep','leave','transfer'].includes(value)){r.action=value;}else if(value){r.studentId=value;r.action='update';}else{r.action='review';}r.confirmed=false;renderYearReview();}
function renderYearReview(){const p=pendingYearChange;if(!p)return;
 const summary=document.getElementById('yearReviewSummary');summary.style.display='block';summary.innerHTML=`<div class="dossier-grid">${dossierField('year','Zielschuljahr',p.schoolYear)}${dossierField('effectiveDate','Klassenzuordnung gültig ab',p.effectiveDate,'date',true)}</div><p>Jede Zeile bleibt korrigierbar. Namensähnlichkeit ist nur ein Vorschlag. Fehlende Kinder bleiben aktiv, sofern du keinen Abgang bestätigst. Zuständigkeiten und Ampelbewertungen bleiben bestehen.</p><p>${p.rows.filter(r=>!r.confirmed).length} Zeilen noch zu prüfen.</p>`;
 summary.insertAdjacentHTML('beforeend','<datalist id="dossierAllStudents">'+data.students.map(s=>'<option value="'+DE(s.last+', '+s.first+' · '+s.id)+'"></option>').join('')+'</datalist>');
 summary.querySelector('[name=year]').onchange=e=>{p.schoolYear=e.target.value;for(const r of p.rows)if(r.pupil)r.pupil.schoolYear=p.schoolYear;};summary.querySelector('[name=effectiveDate]').onchange=e=>p.effectiveDate=e.target.value;
 document.querySelector('#yearReviewModal .dialog').classList.add('wide');document.querySelector('#yearReviewModal thead').innerHTML='<tr><th>Kind / Zuordnung</th><th>Bisher</th><th>Neue Klasse / Grund</th><th>Geprüft</th></tr>';
 document.getElementById('yearReviewTable').innerHTML=p.rows.map((r,i)=>{
 const s=data.students.find(s=>s.id===r.studentId),name=r.pupil?(r.pupil.last+', '+r.pupil.first):s?.last+', '+s?.first;const chosen=r.action==='update'?r.studentId:r.action;
 const candidates=[...new Set([r.studentId,...r.candidates||[]])].filter(Boolean),ordered=data.students.filter(s=>candidates.includes(s.id)).sort((a,b)=>a.last.localeCompare(b.last));
 return `<tr class="dossier-review"><td><strong>${DE(name)}</strong><br><small>${r.missing?'Fehlt in der Liste':r.pupil.givenId?'Kennung: '+DE(r.pupil.givenId):'Ohne verlässliche Kennung: manuell zuordnen'}</small><select aria-label="Akte zuordnen" onchange="dossierYearAction(${i},this.value)"><option value="review">Bitte prüfen …</option>${r.pupil?'<option value="new" '+(chosen==='new'?'selected':'')+'>Geprüfte Neuaufnahme</option>':''}<option value="${r.missing?'keep':'skip'}" ${['keep','skip'].includes(chosen)?'selected':''}>Unverändert lassen</option>${r.studentId?'<option value="leave" '+(chosen==='leave'?'selected':'')+'>Bestätigter Schulabgang</option><option value="transfer" '+(chosen==='transfer'?'selected':'')+'>Bestätigter Schulwechsel</option>':''}${r.pupil?ordered.map(s=>`<option value="${DE(s.id)}" ${chosen===s.id?'selected':''}>${DE(s.last+', '+s.first+' · '+s.className+' · '+s.id)}${s.active===false?' (archiviert)':''}</option>`).join(''):''}</select>${r.pupil?`<input list="dossierAllStudents" placeholder="Andere Akte suchen …" aria-label="Andere Akte suchen" onchange="dossierOtherStudent(${i},this.value)">`:''}</td><td>${DE(s?.className||'–')}<br>${DE(s?.schoolYear||'')}<br>${s?DE(s.id):''}</td><td>${r.pupil?`<input aria-label="Neue Klasse" value="${DE(r.pupil.className)}" onchange="pendingYearChange.rows[${i}].pupil.className=this.value.trim();pendingYearChange.rows[${i}].confirmed=false;renderYearReview()"><input aria-label="Neue Klassenleitung" placeholder="Neue Klassenleitung" value="${DE(p.classLeads[r.pupil.className]||'')}" onchange="pendingYearChange.classLeads[pendingYearChange.rows[${i}].pupil.className]=this.value.trim()"><select aria-label="Art des Wechsels" onchange="pendingYearChange.rows[${i}].reason=this.value">${dossierOptions(['Geprüfte Klassenzuordnung','Reguläre Versetzung','Wiederholung','Überspringen','Parallelklassenwechsel','Schulkindergarten → Klasse 1','Neuaufnahme / Rückkehr'],r.reason||'Geprüfte Klassenzuordnung')}</select>`:'Keine automatische Archivierung'}</td><td><label><input type="checkbox" ${r.confirmed?'checked':''} onchange="pendingYearChange.rows[${i}].confirmed=this.checked"> Geprüft</label></td></tr>`;
 }).join('');document.getElementById('applyYearButton').textContent='Geprüfte Änderungen übernehmen';
}
async function applyYearChange(){if(!pendingYearChange)return;const p=pendingYearChange;const errors=Dossier.validate(data,p);if(errors.length){appAlert(errors.join('\n'));return;}if(!await appConfirm('Geprüfte Änderungen übernehmen? Vorher wird eine vollständige Sicherung einschließlich Dokumenten erstellt.'))return;if(!await exportCompleteBackup('Vor Schuljahreswechsel',false))return;
 const before=data,next=structuredClone(data),plan=structuredClone(p);Dossier.apply(next,plan);data=next;try{await persistState();}catch(err){data=before;appAlert('Nicht gespeichert: '+String(err));return;}pendingYearChange=null;renderAll();closeModal('yearReviewModal');go('students');toast('Bestehende Akten fortgeführt. Offene Aufgaben bleiben sichtbar.');}
// Open tasks remain visible even after confirmed departure.
aufgabeArchiviert=function(t){return false;};
toggleStudentStatus=async function(){const s=data.students.find(s=>s.id===selectedStudentId);if(!s)return;if(s.active!==false){dossierPopup('Schulabgang bestätigen',`<div class="dossier-grid"><label>Grund<select name="reason" class="field">${dossierOptions(['Bestätigter Schulabgang','Bestätigter Schulwechsel'],'')}</select></label>${dossierField('date','Gültig ab',today(),'date',true)}<p class="full">Die gesamte Akte bleibt erhalten. ${Dossier.work(data,s.id).filter(t=>!t.done).length} offene Aufgaben bleiben zur Prüfung sichtbar.</p></div>`,async fd=>{Dossier.archive(data,s.id,fd.get('date'),fd.get('reason'));await dossierSave();closeModal('dossierEditModal');dossierRefresh();});}else{dossierMakePreview([{givenId:s.id,first:s.first,last:s.last,className:s.className,schoolYear:data.settings.currentSchoolYear}],data.settings.currentSchoolYear);}};
const legacyRenderTasks=renderTasks;
renderTasks=function(){legacyRenderTasks();const list=document.getElementById('taskList');list.innerHTML=`<div class="dossier-toolbar"><button class="btn" onclick="dossierCalendar()">Kalender / Aufgabenboard</button></div>`+data.tasks.slice().sort((a,b)=>Number(a.done)-Number(b.done)||String(a.due||'9999').localeCompare(String(b.due||'9999'))).map(t=>`<div class="row ${t.done?'taskdone':''}"><div class="grow"><strong>${DE(t.title)}</strong><span class="subtle">${DE(t.due?fmt(t.due):'Ohne Termin')} · ${DE(t.status||'offen')} · ${DE(t.assignedTo||'nicht festgelegt')}</span><span>${Dossier.ids(data,t).map(sid=>{const s=data.students.find(s=>s.id===sid);return `<button class="linkbutton" onclick="showStudent('${DE(sid)}')">${DE(s?s.first+' '+s.last:'Unklare Zuordnung')}</button>`;}).join(' · ')}</span>${t.assignmentReview?`<p class="notice warning">${DE(t.assignmentReview)}</p>`:''}${t.instructions?`<details><summary>Anleitung</summary><p>${DE(t.instructions)}</p></details>`:''}${t.result?'<p>'+DE(t.result)+'</p>':''}</div><button class="btn" onclick="dossierTask('${DE(t.id)}')">Bearbeiten</button></div>`).join('');};
function dossierCalendar(){const tasks=data.tasks.filter(t=>!t.done).sort((a,b)=>String(a.due||'9999').localeCompare(String(b.due||'9999')));dossierPopup('Termine und Aufgabenboard',`<p>Dieselben Aufgaben wie in der Chronologie. Alle Schuljahre und auch bestätigte Abgänge sind enthalten.</p><div class="dossier-grid">${['offen','in Bearbeitung','wartet auf Rückmeldung'].map(st=>`<section><h3>${DE(st)}</h3>${tasks.filter(t=>(t.status||'offen')===st).map(t=>`<p><button type="button" class="btn" onclick="dossierTask('${DE(t.id)}')">${DE(t.title)}</button><br>${DE(t.due?fmt(t.due):'ohne Termin')} · ${DE(t.assignedTo||'')}</p>`).join('')}</section>`).join('')}</div><h3>Kalender nach Datum</h3>${tasks.filter(t=>t.due).map(t=>`<p>${DE(fmt(t.due))} · <button type="button" class="linkbutton" onclick="dossierTask('${DE(t.id)}')">${DE(t.title)}</button></p>`).join('')}`,async()=>closeModal('dossierEditModal'));}
// Preserve existing recurrence logic for recurring organizational tasks.
const dossierOriginalTask=dossierTask;
dossierTask=function(tid){const t=data.tasks.find(t=>t.id===tid);if(t?.recurrence){openTaskComplete(tid);return;}dossierOriginalTask(tid);};
statDaten=function(){const d=legacyStatDaten();for(const e of Dossier.journalStats(data,'',statKlasse()).filter(e=>imZeitraum(e,d.z))){const row={...e,caseId:data.cases.find(c=>c.studentId===e.participantIds[0])?.id||'',reason:e.type,level:e.participantIds.length>1?'Gruppe':'Einzel'};if(e.participantIds.length>1)d.gruppen.push(row);else d.kontakte.push(row);}return d;};
// All regular entry paths enter the same editor. No case selection is needed.
verlaufOeffnen=function(sid='',type='',origin=null){if(sid)selectedStudentId=sid;dossierEntry(type==='Rückmeldung'?'response':'event',origin?'legacy:'+origin.id:'');};
openClassActivity=function(className=''){dossierEntry('event','',data.students.filter(s=>s.active!==false&&s.className===className).map(s=>s.id));const f=document.getElementById('dossierEditForm');f.elements.type.value='Sozialtraining / Klassentraining / Kleingruppenangebot';};
const oldGroupSubmit=document.getElementById('groupTalkForm').onsubmit;
document.getElementById('groupTalkForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),participantIds=fd.getAll('participantIds');const entry=Dossier.addEntry(data,{...f,participantIds,type:'Gruppengespräch / Konfliktklärung / Vermittlung',title:f.type,content:[f.note,f.result,f.individualNotes?'Früherer unzugeordneter Hinweis: '+f.individualNotes:''].filter(Boolean).join('\n')||f.type});if(f.due)Dossier.addTask(data,{title:'Rückmeldung: '+f.type,assignedTo:f.responsible||'Zuständigkeit prüfen',due:f.due,participantIds,sourceEntryKey:'entry:'+entry.id});await dossierSave();closeModal('groupTalkModal');showStudent(participantIds[0]);};
// The original task completion entry point also opens the shared status editor.
const oldTaskComplete=openTaskComplete;
openTaskComplete=function(tid){const t=data.tasks.find(t=>t.id===tid);if(t?.recurrence)return oldTaskComplete(tid);dossierOriginalTask(tid);};
// Expose documentation from Settings and preserve the familiar desktop application.
const help=document.createElement('div');help.className='card';help.innerHTML='<h3>Chronologie und Schuljahreswechsel</h3><p>Ein Kind, eine dauerhafte Akte. Anleitung zur neuen Bedienung, zu Import und Sicherung.</p><button class="btn" onclick="dossierHandbook()">Handbuch öffnen</button>';document.getElementById('settings').append(help);
function dossierHandbook(){dossierPopup('Handbuch · Version 0.10.0',`<p>Öffne unter Schüler:innen ein Kind. „Ereignis / Gespräch eintragen“ dokumentiert den Inhalt; „Information hinzufügen“ reicht für Zusatzwissen wie Ergotherapie. Die Akte ist automatisch zugeordnet.</p><p>Weitere Kinder wählst du unter „Zuordnung prüfen“. Nur tatsächlich Teilnehmende markieren. Gemeinsame Inhalte werden einmal gespeichert; individuelle Ergänzungen erscheinen nur beim ausgewählten Kind.</p><p>Die Zeitleiste verläuft von früher nach später und öffnet bei „Heute“. Geplante Einträge sind gestrichelt und bleiben unbestätigt, bis du sie ausdrücklich bearbeitest. Aufgaben ohne Termin stehen unten. Überfällige Aufgaben sind bei Heute verlinkt.</p><p>Am Eintrag kannst du mehrere nächste Schritte, Rückmeldungen und Überprüfungen verknüpfen. Zuständigkeiten und Fristen bestimmst du selbst. Statusänderungen und Verschiebungen bleiben nachvollziehbar. Aufgabenliste, Kalender und Aufgabenboard zeigen dieselben Datensätze.</p><p>Die fachliche Ampel wird mit Begründung, Datum und Person eingetragen. Berechnete Fehlzeitenhinweise bleiben davon getrennt. Ein Schuljahreswechsel ändert die Bewertung nicht.</p><p>Unter Schüler:innen kannst du eine CSV prüfen oder „Wechsel ohne Import vorbereiten“ wählen. Korrigiere Aktenzuordnung, Klasse, Klassenleitung, Wechselart und Gültig-ab-Datum. Namensgleichheit ist kein automatischer Treffer. Verlässliche externe Kennungen werden nach Prüfung gespeichert. Ohne Kennung verwendest du künftig die exportierte Klassenliste mit der stabilen Schüler-ID.</p><p>Fehlende Kinder bleiben unverändert. Bestätigte Abgänge werden einzeln archiviert; offene Aufgaben bleiben sichtbar. Vor dem Wechsel wird eine Gesamtsicherung erstellt. Vergangene Klassen bleiben an den Einträgen erhalten. Unbekannte historische Daten werden als unbekannt angezeigt.</p><p>Beim ersten Öffnen einer älteren Version wird vor der Datenanpassung eine verschlüsselte Sicherung im Sicherungsordner des Datentresors erstellt. Der Schuljahresfilter blendet nur aus. Dokumente verbleiben in der bestehenden Akte.</p><p>Alte, keinem Kind verlässlich zugeordnete Einträge müssen manuell geprüft werden. Aus Freitext entstehen keine automatischen Diagnosen, Aufgaben oder Personenzuordnungen.</p>`,async()=>closeModal('dossierEditModal'));}

openGroupTalk=function(){selectedStudentId='';dossierEntry('event');document.getElementById('dossierEditForm').elements.type.value='Gruppengespräch / Konfliktklärung / Vermittlung';};

function dossierOtherStudent(i,value){const s=data.students.find(s=>s.last+', '+s.first+' · '+s.id===value);if(s)dossierYearAction(i,s.id);else appAlert('Bitte eine Akte aus den Suchvorschlägen auswählen.');}
